// add constants here
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_COMPANY = 'GET_COMPANY';
export const COMPANY_ERROR = 'COMPANY_ERROR';
export const GET_FAV_PRODUCTS = 'GET_FAV_PRODUCTS';
export const FAV_PRODUCTS_ERROR= 'FAV_PRODUCTS_ERROR';
export const GET_RECENT_PRODUCTS = 'GET_RECENT_PRODUCTS';
export const RECENT_PRODUCTS_ERROR = 'RECENT_PRODUCTS_ERROR';
export const GET_RECENT_ORDERS = 'GET_RECENT_ORDERS';
export const RECENT_ORDERS_ERROR = 'RECENT_ORDERS_ERROR';
